export const GET_HISTORY = "GET_HISTORY";
export const GET_HISTORY_FAILED = "GET_HISTORY_FAILED";

export const GET_DOWNLOADED_SONGS = "GET_DOWNLOADED_SONGS";
export const GET_DOWNLOADED_SONGS_FAILED = "GET_DOWNLOADED_SONGS_FAILED";
