export const MUSIC_GET_TRENDING = "MUSIC_GET_TRENDING";
export const MUSIC_GET_TRENDING_FAILED = "MUSIC_GET_TRENDING_FAILED";
export const MUSIC_GET_EXPLORE = "MUSIC_GET_EXPLORE";
export const MUSIC_GET_EXPLORE_FAILED = "MUSIC_GET_EXPLORE_FAILED";
export const GET_PLAYLIST = "GET_PLAYLIST";
export const GET_PLAYLIST_FAILED = "GET_PLAYLIST_FAILED";
export const GET_NEW_RELEASES = "GET_NEW_RELEASES";
export const GET_NEW_RELEASES_FAILED = "GET_NEW_RELEASES_FAILED";
export const GET_MOODS_AND_GENRES = "GET_MOODS_AND_GENRES";
export const GET_MOODS_AND_GENRES_FAILED = "GET_MOODS_AND_GENRES_FAILED";
export const GET_MOODS_AND_GENRES_DATA = "GET_MOODS_AND_GENRES_DATA";
export const GET_MOODS_AND_GENRES_DATA_FAILED =
  "GET_MOODS_AND_GENRES_DATA_FAILED";
export const GET_RECOMMENDED_PLAYLIST = "GET_RECOMMENDED_PLAYLIST";
export const GET_RECOMMENDED_PLAYLIST_FAILED =
  "GET_RECOMMENDED_PLAYLIST_FAILED";

export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const GET_PLAYLISTS_DATA = "GET_PLAYLISTS_DATA";
export const GET_PLAYLISTS_DATA_FAILED = "GET_PLAYLISTS_DATA_FAILED";

export const SEARCH_TRACK = "SEARCH_TRACK";
export const SEARCH_TRACK_FAILED = "SEARCH_TRACK_FAILED";

export const GET_TRACK_AUDIO = "GET_TRACK_AUDIO";
export const GET_TRACK_AUDIO_FAILED = "GET_TRACK_AUDIO_FAILED";

export const PLAY_SEARCHED_TRACK = "PLAY_SEARCHED_TRACK";
export const PLAY_SEARCHED_TRACK_FAILED = "PLAY_SEARCHED_TRACK_FAILED";

export const PLAY_PLAYLIST_TRACK = "PLAY_PLAYLIST_TRACK";
export const PLAY_PLAYLIST_TRACK_FAILED = "PLAY_PLAYLIST_TRACK_FAILED";

export const PLAY_ALL_PLAYLIST_TRACK = "PLAY_ALL_PLAYLIST_TRACK";
export const PLAY_ALL_PLAYLIST_TRACK_FAILED = "PLAY_ALL_PLAYLIST_TRACK_FAILED";

export const PLAY_DOWNLOADED_SONGS = "PLAY_DOWNLOADED_SONGS";
export const PLAY_DOWNLOADED_SONGS_FAILED = "PLAY_DOWNLOADED_SONGS_FAILED";

export const GET_ARTIST = "GET_ARTIST";
export const GET_ARTIST_FAILED = "GET_ARTIST_FAILED";

export const GET_ALBUM = "GET_ALBUM";
export const GET_ALBUM_FAILED = "GET_ALBUM_FAILED";

export const SHUFFLE_PLAY_ALL_PLAYLIST_TRACK =
  "SHUFFLE_PLAY_ALL_PLAYLIST_TRACK";
export const SHUFFLE_PLAY_ALL_PLAYLIST_TRACK_FAILED =
  "SHUFFLE_PLAY_ALL_PLAYLIST_TRACK_FAILED";

export const SHUFFLE_PLAY_ALL_ARTIST_TRACK = "SHUFFLE_PLAY_ALL_ARTIST_TRACK";
export const SHUFFLE_PLAY_ALL_ARTIST_TRACK_FAILED =
  "SHUFFLE_PLAY_ALL_ARTIST_TRACK_FAILED";

export const PLAY_ALL_ARTIST_TRACK = "PLAY_ALL_ARTIST_TRACK";
export const PLAY_ALL_ARTIST_TRACK_FAILED = "PLAY_ALL_ARTIST_TRACK_FAILED";
